# Generated by Django 4.2.7 on 2026-02-09 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('complete', 'Complétée'), ('suspendue', 'Suspendue')], default='complete', max_length=15)),
                ('notes_supplementaires', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('neurologie', 'Neurologie'), ('pediatrie', 'Pédiatrie'), ('psychiatrie', 'Psychiatrie'), ('chirurgie', 'Chirurgie'), ('ophtalmologie', 'Ophtalmologie'), ('dentiste', 'Dentiste'), ('autre', 'Autre')], max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_licence', models.CharField(max_length=20, unique=True)),
                ('adresse_cabinet', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('composition', models.TextField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('fabricant', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordonnance', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('instructions', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='api.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='api.medecin')),
            ],
            options={
                'ordering': ['-date_ordonnance'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_secu', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('complete', 'Complété'), ('reporte', 'Reporté')], default='confirme', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='api.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='api.patient')),
            ],
            options={
                'ordering': ['-date_heure'],
                'unique_together': {('medecin', 'date_heure')},
            },
        ),
        migrations.CreateModel(
            name='OrdonnanceMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='api.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='api.patient'),
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_facturation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Paiement partiel'), ('impaye', 'Impayé'), ('annule', 'Annulé')], default='impaye', max_length=15)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturations', to='api.patient')),
            ],
            options={
                'ordering': ['-date_facturation'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.medecin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rendezvous'),
        ),
    ]
